---
- name: gather router information
  hosts: juniper
  connection: local
  gather_facts: no
  tasks:
    - name: gather junos_facts
      junos_facts:
      register: version

    - debug:
        msg: "{{version}}"