---
- name: backup router configurations
  hosts: juniper
  connection: network_cli
  gather_facts: no
  tasks:
    - name: gather junos_facts
      junos_facts:
      register: version

    - debug:
        msg: "{{version}}"