---
- name: Configure GRE Tunnel between rtr1 and rtr2
  hosts: juniper
  gather_facts: no
  connection: local
  vars:
    rtr3_public_ip: "{{hostvars['rtr3']['ansible_host']}}"
    rtr4_public_ip: "{{hostvars['rtr4']['ansible_host']}}"
  tasks:
    tasks:
    - name: create tunnel interface to R2
      ios_config:
        lines:
         - 'ip address 10.0.0.1 255.255.255.0'
         - 'tunnel source GigabitEthernet1'
         - 'tunnel destination {{rtr2_public_ip}}'
        parents: interface Tunnel 0
      when:
        - '"rtr1" in inventory_hostname'
        
        
    - name: create tunnel interface to R1
      ios_config:
        lines:
         - 'ip address 10.0.0.2 255.255.255.0'
         - 'tunnel source GigabitEthernet1'
         - 'tunnel destination {{rtr1_public_ip}}'
        parents: interface Tunnel 0
      when:
        - '"rtr2" in inventory_hostname'