---
- name: backup router configuration
  hosts: juniper
  connection: local
  gather_facts: no
  tasks:
    - name: gather junos_facts
      junos_facts:
      register: version

    - debug:
        msg: "{{version}}"

    - name: Backup configuration
      junos_config:
        backup: yes