---
- name: RESTORE CONFIGURATION
  hosts: cisco
  connection: local
  gather_facts: no

  tasks:
    - name: gather_ios facts
      ios_facts:
      register: iosfact
    
    - name: copy file at root dir of flash
      net_put:
        src: ./backup/{{inventory_hostname}}.config


    - name: CONFIG REPLACE
      ios_command:
        commands:
          - config replace flash:{{inventory_hostname}}.config force