---
- name: Download Config from SCM
  hosts: tag_Name_linklight_student1_ansible
  connection: local
  gather_facts: no
  tasks:
  
    - name: Remove any previous config files
      shell: 'rm -rf /tmp/rtr*' 
      
    - name: Download latest rtr1 config file
      get_url: 
        url: https://raw.githubusercontent.com/etg-ansible-demo/Networks/master/ios_rtr1.config
        dest: /tmp/rtr1.config
        owner: awx
        group: awx
        mode: 0644 

    - name: Download latest rtr2 config file
      get_url: 
        url: https://raw.githubusercontent.com/etg-ansible-demo/Networks/master/ios_rtr2.config
        dest: /tmp/rtr2.config
        owner: awx
        group: awx
        mode: 0644