---
- name: RESTORE CONFIGURATION
  hosts: cisco
  connection: local
  gather_facts: no

  tasks:
    - name: COPY RUNNING CONFIG TO ROUTER
      command: scp -i /home/student1/.ssh/aws-private.pem ./backup/{{inventory_hostname}}.config ec2-user@{{inventory_hostname}}:/{{inventory_hostname}}.config

    - name: CONFIG REPLACE
      ios_command:
        commands:
          - config replace flash:{{inventory_hostname}}.config force